routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', function () {
	return redirect('login');
});



Route::group(['middleware' => 'cekstatus'], function() {
	/* --------------------- Dashboard --------------------- */
Route::resource('dashboards', 'V1\Backoffice\DashboardController');
Route::get('backoffice', 'V1\Backoffice\DashboardController@index');
Route::get('backoffice', 'V1\Backoffice\DashboardController@index');
Route::get('dashboard', 'V1\Backoffice\DashboardController@showDashboard');
Route::get('detail_project', 'V1\Backoffice\DashboardController@detail_project');
Route::get('imports', 'V1\Backoffice\DashboardController@import');

/* --------------------- End Project --------------------- */


/* --------------------- Project --------------------- */
Route::resource('projects', 'V1\Backoffice\ProjectController');
Route::get('dashboard_divisions/{id}', 'V1\Backoffice\ProjectController@showDivision');

/* --------------------- End Project --------------------- */


/* --------------------- Project Progress--------------------- */
Route::resource('projects_progress', 'V1\Backoffice\ProjectProgressController');
Route::get(
	'create_progress',
	'V1\Backoffice\ProjectProgressController@create_progress'
);
/* --------------------- End Project --------------------- */

/* --------------------- Project Budget--------------------- */
Route::resource('projects_budget', 'V1\Backoffice\ProjectBudgetController');
Route::get(
	'create_budget',
	'V1\Backoffice\ProjectBudgetController@create_budget'
);
/* --------------------- End Project Budget --------------------- */

/* --------------------- Detail Project --------------------- */
Route::resource('detail_projects', 'V1\Backoffice\DetailProjectController');
/* --------------------- End Detail Project --------------------- */

/* --------------------- Detail Project --------------------- */
Route::resource('divisions', 'V1\Backoffice\DivisionController');
/* --------------------- End Detail Project --------------------- */



/* --------------------- Activity --------------------- */
Route::resource('activities', 'V1\Backoffice\ActivityController');
Route::post('/storeExcelActivity', 'V1\Backoffice\ActivityController@storeExcelActivity');
Route::post('/storeExcelActivityDelivery', 'V1\Backoffice\ActivityController@storeExcelActivityDelivery');
Route::get('activity_delivery/{id}', 'V1\Backoffice\ActivityController@showDelivery');

/* --------------------- End Activity ---------------------*/

/* --------------------- Sub Activity --------------------- */
Route::resource('sub_activities', 'V1\Backoffice\SubActivityController');
Route::post('/storeExcelSubActivity', 'V1\Backoffice\SubActivityController@storeExcelSubActivity');
Route::get('sub_technology/{id}', 'V1\Backoffice\SubActivityController@showTechnology');
Route::get('sub_delivery/{id}', 'V1\Backoffice\SubActivityController@showDelivery');
/* --------------------- End Sub Activity ---------------------*/

/* --------------------- Work Activity --------------------- */
Route::resource('work_activities', 'V1\Backoffice\WorkActivityController');
Route::post('/storeExcelWorkActivity', 'V1\Backoffice\WorkActivityController@storeExcelWorkActivity');
Route::get('type_technology/{id}', 'V1\Backoffice\WorkActivityController@showTechnology');

/* --------------------- End Work Activity ---------------------*/

/* Update for checklist activity */
Route::post('/updateDelivery', 'V1\Backoffice\ActivityController@updateTaskDelivery');
Route::post('/update/{id}', 'V1\Backoffice\WorkActivityController@updateTask');
Route::post('/updatePic', 'V1\Backoffice\WorkActivityController@updatePic');

/* ---------------------End Detail Work Activity --------------------- */

/* --------------------- Late Report --------------------- */
Route::resource('late_history', 'V1\Backoffice\LateHistoryController');
Route::get('report_latehistories_teknologi', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_teknologi');
Route::get('report_latehistories_logistik', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_logistik');
Route::get('report_latehistories_fabrikasi', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_fabrikasi');
Route::get('report_latehistories_finishing', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_finishing');
Route::get('report_latehistories_testing', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_testing');
Route::get('report_latehistories_delivery', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_delivery');
/* --------------------- End Late Report --------------------- */


/* --------------------- Master Data --------------------- */
Route::resource('masters', 'V1\Backoffice\MasterDataController');
Route::get('master_activities', 'V1\Backoffice\MasterDataController@showSubActivity');
Route::get('master_sub_activities', 'V1\Backoffice\MasterDataController@showWorkActivity');
Route::get('report_master_activity', 'V1\Backoffice\MasterDataController@cetak_laporan_activity');
Route::get('report_master_sub_activity', 'V1\Backoffice\MasterDataController@cetak_laporan_sub_activity');
Route::get('report_master_work_activity', 'V1\Backoffice\MasterDataController@cetak_laporan_work_activity');

/* --------------------- End Master Data --------------------- */

/* --------------------- Manage User Data --------------------- */
Route::resource('auths', 'V1\Backoffice\AuthController');
Route::resource('profiles', 'V1\Backoffice\ProfileController');
Route::get('registration', 'V1\Backoffice\AuthController@showFormRegister');
/* --------------------- End Master Data --------------------- */


/* --------------------- Manage Issues  --------------------- */
Route::resource('issues', 'V1\Backoffice\IssueController');
Route::get(
	'create_issue',
	'V1\Backoffice\IssueController@create_issue'
);


Route::get(
	'{id}/master_activity',
	'V1\Backoffice\IssueController@get_master_activity'
);

Route::get(
	'{id}/divisions',
	'V1\Backoffice\IssueController@get_divisions'
);



Route::get(
	'create_issue',
	'V1\Backoffice\IssueController@create_issue'
);
Route::get('create_issue/{id}/sub_activity', 'V1\Backoffice\IssueController@get_sub_activity');
Route::get('create_issue/{id}/work_activity', 'V1\Backoffice\IssueController@get_work_activity');
Route::get(
	'data_issue',
	'V1\Backoffice\IssueController@issue'
);

// Cetak isu report
Route::get('report_issue_teknologi/', 'V1\Backoffice\IssueController@cetak_laporan_isu_teknologi');
Route::get('report_issue_logistik', 'V1\Backoffice\IssueController@cetak_laporan_isu_logistik');
Route::get('report_issue_fabrikasi', 'V1\Backoffice\IssueController@cetak_laporan_isu_fabrikasi');
Route::get('report_issue_finishing', 'V1\Backoffice\IssueController@cetak_laporan_isu_finishing');
Route::get('report_issue_testing', 'V1\Backoffice\IssueController@cetak_laporan_isu_testing');

/* --------------------- End Issues --------------------- */

/* --------------------- Data Notification History --------------------- */
Route::resource('notifications', 'V1\Backoffice\NotificationController');
Route::get(
	'warning_notifications',
	'V1\Backoffice\NotificationController@showWarning'
);
/* --------------------- ENd Notification History --------------------- */


/* --------------------- Reports Data --------------------- */
Route::resource('reports', 'V1\Backoffice\ReportController');
/* --------------------- End Report Data --------------------- */


/* --------------------- Histories Data --------------------- */
Route::resource('histories', 'V1\Backoffice\HistoryController');
Route::get('report_histories_teknologi', 'V1\Backoffice\HistoryController@cetak_laporan_teknologi');
Route::get('report_histories_logistik', 'V1\Backoffice\HistoryController@cetak_laporan_logistik');
Route::get('report_histories_fabrikasi', 'V1\Backoffice\HistoryController@cetak_laporan_fabrikasi');
Route::get('report_histories_finishing', 'V1\Backoffice\HistoryController@cetak_laporan_finishing');
Route::get('report_histories_testing', 'V1\Backoffice\HistoryController@cetak_laporan_testing');
/* --------------------- End Report Data --------------------- *

Route::get('/home', 'HomeController@index')->name('home');

/* --------------------- Pie chart detail --------------------- */

Route::get('
	dashboard_divisions/{id}/{status_name}/{division_id}', 'V1\Backoffice\ProjectController@showDetailPieChartAdmin');

Route::get('
    dashboard_divisions/{id}/{status_name}', 'V1\Backoffice\ProjectController@showDetailPieChartDivision');

/* --------------------- End Pie chart detail --------------------- */

/* --------------------- Count At Sidebar --------------------- */

Route::get(
	'count_finish',
	'V1\Backoffice\NotificationController@countFinish'
);

Route::get(
	'count_warning',
	'V1\Backoffice\NotificationController@countWarning'
);

Route::get(
	'count_late',
	'V1\Backoffice\NotificationController@countLate'
);

Route::get(
	'count_issue',
	'V1\Backoffice\NotificationController@countIssue'
);
/* --------------------- End Count At Sidebar --------------------- */

/* --------------------- Count At Navbar --------------------- */
Route::get(
	'notif',
	'V1\Backoffice\NotificationController@show'
);
/* --------------------- End Count At Navbar --------------------- */


/* ---------------------  Division Additional --------------------- */

app/Http/Controllers/V1/Backoffice/AuthController.php
<?php

namespace App\Http\Controllers\V1\Backoffice;

use App\Entities\Division;
use App\Entities\Role;
use App\Entities\Project;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;

class AuthController extends Controller
{
    /**
     * Show the page registration.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $user = User::with(['get_role'])->orderBy('users.id','DESC')->get();
        return view('backoffice.users.data_users', compact('user'));
    }

    /**
     * Show the form registration.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function showFormRegister()
    {
        $project    = Project::all();
        $role       = Role::all();
        $division   = Division::all();
        return view('backoffice.users.register', compact('role','division','project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'          => 'required', 'string', 'max:255',
            'username'      => 'required', 'string', 'max:255',
            'nip'           => 'required', 'max:255', 'unique:users',
            'phone'         => 'required', 'max:15',
            'email'         => 'required', 'string', 'email', 'max:255', 'unique:users',
            'password'      => 'required', 'string', 'min:3',
            'division_name' => 'required',
            'role_id'       => 'required',
        ]);

        $user = new User([
            'name'          => $request->get('name'),
            'username'      => $request->get('username'),
            'nip'           => $request->get('nip'),
            'email'         => $request->get('email'),
            'phone'         => $request->get('phone'),
            'division_name' => $request->get('division_name'),
            'password'      => Hash::make($request->get('password')),
            'role_id'       => $request->get('role_id'),
            'project_to_pm' => $request->get('project_to_pm'),
        ]);
        $user->save();
        alert()->success('Successfully Add Data.', 'Success!');
        return redirect('/auths');
    }

    /**
     * Show the form for editing user.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user       = User::find($id);
        $role       = Role::all();
        $project    = Project::all();
        $division   = Division::all();
        return view('backoffice.users.edit', compact('user','role','division','project'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        if(empty($request->password)){
            $user->name         = $request->get('name');
            $user->username     = $request->get('username');
            $user->nip           = $request->get('nip');
            $user->email         = $request->get('email');
            $user->phone         = $request->get('phone');
            $user->division_name = $request->get('division_name');
            $user->role_id       = $request->get('role_id');
            $user->project_to_pm = $request->get('project_to_pm');
            $user->save();
        } else {
            $user->name         = $request->get('name');
            $user->username     = $request->get('username');
            $user->nip           = $request->get('nip');
            $user->email         = $request->get('email');
            $user->phone         = $request->get('phone');
            $user->division_name = $request->get('division_name');
            $user->password      = Hash::make($request->get('password'));
            $user->role_id       = $request->get('role_id');
            $user->project_to_pm = $request->get('project_to_pm');
            $user->save();
        }
        alert()->success('Successfully Update Data.', 'Success!');
        return redirect('/auths');
    }


    /** 
     * Remove the specified resou   rce from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        alert()->success('Successfully Remove Data.', 'Success!');
        return redirect('/auths');
    }


}

app/Http/Controllers/V1/Backoffice/MasterDataController.php
<?php

namespace App\Http\Controllers\V1\Backoffice;

use App\Http\Controllers\Controller;
use App\Entities\Activity;
use App\Entities\WorkActivity;
use App\Entities\SubActivity;
use Illuminate\Http\Request;
use PDF;
use DB;

class MasterDataController extends Controller
{
    /**
     * master activity page all
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $activities = Activity::with('get_division')->get();
        return view('backoffice.masters.master_activity', compact('activities'));
    }

    /**
     * master sub activity page all
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function showSubActivity(Request $request)
    {
        $sub_activities = SubActivity::with('get_activity')->get();
        return view('backoffice.masters.master_sub_activity', compact('sub_activities'));
    }


    /**
     * master sub activity page all
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function showWorkActivity(Request $request)
    {
        $work_activities = WorkActivity::with('get_sub_activity')->get();
        return view('backoffice.masters.master_work_activity', compact('work_activities'));
    }

    public function cetak_laporan_activity()
    {
        $activities = Activity::with('get_division')->get();
        ini_set('memory_limit', '8192M');
        $pdf = PDF::loadview('backoffice.masters.report_master_activity', ['activities'=>$activities]);
        set_time_limit(600);
        return $pdf->download('report-master-activity.pdf');

    }

    public function cetak_laporan_sub_activity()
    {
        $sub_activities = SubActivity::with('get_activity')->get();
        ini_set('memory_limit', '8192M');
        $pdf = PDF::loadview('backoffice.masters.report_master_sub_activity', ['sub_activities'=>$sub_activities]);
        set_time_limit(600);
        return $pdf->download('report-master-sub-activity.pdf');

    }

    public function cetak_laporan_work_activity()
    {
        $work_activities = WorkActivity::with('get_sub_activity')->get();
        ini_set('memory_limit', '8192M');
        $pdf = PDF::loadview('backoffice.masters.report_master_work_activity', ['work_activities'=>$work_activities]);
        set_time_limit(600);
        return $pdf->download('report-master-work-activity.pdf');

    }
}

resources/views/backoffice/reports/edit.blade.php
@extends('layouts.backend.masterPage')
@section('content')
<div class="section-header">
    <h1 class="title">Edit Laporan</h1>
    <div class="section-header-breadcrumb">
        <a class="btn btn-primary btn-sm" href="{{ URL::previous() }}"><i class="fas fa-arrow-left"></i> Back</a>
    </div>
</div>
<div class="card top">
    <div class="card-body">
        <h4 class="titleC text-center">Form Edit Laporan</h4><br>
        <div class="basic-form">
                <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{{ route('reports.update',$data->id) }}">
                    @method('PATCH')
                    @csrf
                    @if ($errors->any())
                    <div class="col-md-10">
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                    @endif 
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Name</label>
                        <input required type="text" name="name" value="{{$data->name}}" placeholder="Input Laporan name" class="form-control">
                    </div>

                    <div class="form-group col-md-6">
                        <label>File</label>
                        <input type="file" value="{{$data->file}}" name="file" class="form-control">
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputState">Project <span class="text-danger">*</span></label>
                        <select class="form-control" name="project_id" required>
                            <option selected>Pilih Project</option>
                            @foreach($project as $row)
                            <option value="{{$row->id}}" {{ $data->get_project->id == $row->id ? 'selected' : '' }}>{{$row->name}}</option>
                            @endforeach
                        </select>
                    </div>


                    <div class="form-group col-md-6">
                        <label> Date</label>
                        <input required type="date" name="date" value="{{$data->date}}" class="form-control">
                    </div>
                </div>

                <div class="form-group">
                    <label>Description</label>
                    <textarea name="description" class="form-control" cols="50" placeholder="Deskripsi Laporan">{{$data->description}}</textarea>
                </div>
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-primary"></input>
                </div>
                
            </form>
        </div>
    </div>
 </div>     
 @endsection  

resources/views/backoffice/reports/report.blade.php
@extends('layouts.backend.masterPage')
@section('content')
<div class="section-header">
    <h1 class="titleC">Master Laporan</h1>
    <div class="section-header-breadcrumb">
        <div class="bottom text-right">
            <button id="modal-5" class="btn btn-sm mb-1 btn-primary"><i class="fa fa-plus"></i> Add Laporan</button>
        </div>
    </div>
     @error('project_id')
               <script type="text/javascript">
                     Swal.fire({
                      icon: 'error',
                      title: 'Oops...',
                      text: 'Pilih Project Harus Terisi',
                    })
               </script>
    @enderror
</div>
<div class="card top">
    @include('sweet::alert')

    <div class="card-body">
        <div class="col-lg-12">
            <!-- Form Modal Report -->
            <form enctype="multipart/form-data" class="modal-part" id="modal-login-part" method="post" action="{{ route('reports.store') }}">
                @csrf
                <div class="form-group">
                    <label>Name</label>
                    <input required type="text" name="name" placeholder="Input Laporan name" class="form-control">
                </div>

                <div class="form-group">
                    <label>File</label>
                    <input required type="file" name="file" class="form-control">
                </div>

                <select class="form-control @error('project_id') is-invalid @enderror" name="project_id" required>
                    <option selected value=''>Pilih Project</option>
                    @foreach($project as $row)
                    <option value="{{$row->id}}">{{$row->name}}</option>
                    @endforeach
                </select>
                @error('project_id')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror

                <div class="form-group">
                    <label>Description</label>
                    <textarea name="description" class="form-control" cols="50" placeholder="Deskripsi Laporan"></textarea>
                </div>

                <div class="form-group">
                    <label> Date</label>
                    <input required type="date" name="date" class="form-control">
                </div>
            </form>
            <!-- End Form Modal Report -->

            <div class="col-md-8">
                <p></p>
            </div>
            <div class="table-responsive">
                <table class="table col-lg-12 zero-configuration" id="exampledr">
                    
                    <thead>
                        <tr>
                            <th width="10%">No.</th>
                            <th width="10%">Name</th>
                            <th width="20%">File</th>
                            <th width="10%">Project</th>
                            <th width="20%">Description</th>
                            <th width="10%">Date</th>
                            <th width="20%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($report as $index => $row)
                        <tr>
                            <td>{{$index+1}}.</td>
                            <td>{{$row->name}}</td>
                            <td>
                                <a href="/laporan/{{$row->file}}" target="_blank">{{$row->file}}</a>
                            </td>
                            <td>{{$row->get_project->name}}</td>
                            <td>{{$row->description}}</td>
                            <td>
                                <?php
                                $date = date_create($row->date);
                                echo date_format($date, "j F Y");
                                ?>
                            </td>
                            <td>
                                <form action="{{ route('reports.destroy', $row->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')

                                    <a onclick="return confirm('Are you sure to delete this data?')">
                                        <button class="btn btn-icon btn-danger" type="submit">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </a>

                                    <a href="{{ route('reports.edit', $row->id)}}">
                                        <button class="btn btn-icon btn-info" type="button">
                                            <i class="fas fa-edit"></i>

                                        </button>
                                    </a>

                                </form>
                            </td>

                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection