routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', function () {
	return redirect('login');
});



Route::group(['middleware' => 'cekstatus'], function() {
	/* --------------------- Dashboard --------------------- */
Route::resource('dashboards', 'V1\Backoffice\DashboardController');
Route::get('backoffice', 'V1\Backoffice\DashboardController@index');
Route::get('backoffice', 'V1\Backoffice\DashboardController@index');
Route::get('dashboard', 'V1\Backoffice\DashboardController@showDashboard');
Route::get('detail_project', 'V1\Backoffice\DashboardController@detail_project');
Route::get('imports', 'V1\Backoffice\DashboardController@import');

/* --------------------- End Project --------------------- */


/* --------------------- Project --------------------- */
Route::resource('projects', 'V1\Backoffice\ProjectController');
Route::get('dashboard_divisions/{id}', 'V1\Backoffice\ProjectController@showDivision');

/* --------------------- End Project --------------------- */


/* --------------------- Project Progress--------------------- */
Route::resource('projects_progress', 'V1\Backoffice\ProjectProgressController');
Route::get(
	'create_progress',
	'V1\Backoffice\ProjectProgressController@create_progress'
);
/* --------------------- End Project --------------------- */

/* --------------------- Project Budget--------------------- */
Route::resource('projects_budget', 'V1\Backoffice\ProjectBudgetController');
Route::get(
	'create_budget',
	'V1\Backoffice\ProjectBudgetController@create_budget'
);
/* --------------------- End Project Budget --------------------- */

/* --------------------- Detail Project --------------------- */
Route::resource('detail_projects', 'V1\Backoffice\DetailProjectController');
/* --------------------- End Detail Project --------------------- */

/* --------------------- Detail Project --------------------- */
Route::resource('divisions', 'V1\Backoffice\DivisionController');
/* --------------------- End Detail Project --------------------- */



/* --------------------- Activity --------------------- */
Route::resource('activities', 'V1\Backoffice\ActivityController');
Route::post('/storeExcelActivity', 'V1\Backoffice\ActivityController@storeExcelActivity');
Route::post('/storeExcelActivityDelivery', 'V1\Backoffice\ActivityController@storeExcelActivityDelivery');
Route::get('activity_delivery/{id}', 'V1\Backoffice\ActivityController@showDelivery');

/* --------------------- End Activity ---------------------*/

/* --------------------- Sub Activity --------------------- */
Route::resource('sub_activities', 'V1\Backoffice\SubActivityController');
Route::post('/storeExcelSubActivity', 'V1\Backoffice\SubActivityController@storeExcelSubActivity');
Route::get('sub_technology/{id}', 'V1\Backoffice\SubActivityController@showTechnology');
Route::get('sub_delivery/{id}', 'V1\Backoffice\SubActivityController@showDelivery');
/* --------------------- End Sub Activity ---------------------*/

/* --------------------- Work Activity --------------------- */
Route::resource('work_activities', 'V1\Backoffice\WorkActivityController');
Route::post('/storeExcelWorkActivity', 'V1\Backoffice\WorkActivityController@storeExcelWorkActivity');
Route::get('type_technology/{id}', 'V1\Backoffice\WorkActivityController@showTechnology');

/* --------------------- End Work Activity ---------------------*/

/* Update for checklist activity */
Route::post('/updateDelivery', 'V1\Backoffice\ActivityController@updateTaskDelivery');
Route::post('/update/{id}', 'V1\Backoffice\WorkActivityController@updateTask');
Route::post('/updatePic', 'V1\Backoffice\WorkActivityController@updatePic');

/* ---------------------End Detail Work Activity --------------------- */

/* --------------------- Late Report --------------------- */
Route::resource('late_history', 'V1\Backoffice\LateHistoryController');
Route::get('report_latehistories_teknologi', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_teknologi');
Route::get('report_latehistories_logistik', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_logistik');
Route::get('report_latehistories_fabrikasi', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_fabrikasi');
Route::get('report_latehistories_finishing', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_finishing');
Route::get('report_latehistories_testing', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_testing');
Route::get('report_latehistories_delivery', 'V1\Backoffice\LateHistoryController@cetak_laporan_late_delivery');
/* --------------------- End Late Report --------------------- */


/* --------------------- Master Data --------------------- */
Route::resource('masters', 'V1\Backoffice\MasterDataController');
Route::get('master_activities', 'V1\Backoffice\MasterDataController@showSubActivity');
Route::get('master_sub_activities', 'V1\Backoffice\MasterDataController@showWorkActivity');
Route::get('report_master_activity', 'V1\Backoffice\MasterDataController@cetak_laporan_activity');
Route::get('report_master_sub_activity', 'V1\Backoffice\MasterDataController@cetak_laporan_sub_activity');
Route::get('report_master_work_activity', 'V1\Backoffice\MasterDataController@cetak_laporan_work_activity');

/* --------------------- End Master Data --------------------- */

/* --------------------- Manage User Data --------------------- */
Route::resource('auths', 'V1\Backoffice\AuthController');
Route::resource('profiles', 'V1\Backoffice\ProfileController');
Route::get('registration', 'V1\Backoffice\AuthController@showFormRegister');
/* --------------------- End Master Data --------------------- */


/* --------------------- Manage Issues  --------------------- */
Route::resource('issues', 'V1\Backoffice\IssueController');
Route::get(
	'create_issue',
	'V1\Backoffice\IssueController@create_issue'
);


Route::get(
	'{id}/master_activity',
	'V1\Backoffice\IssueController@get_master_activity'
);

Route::get(
	'{id}/divisions',
	'V1\Backoffice\IssueController@get_divisions'
);



Route::get(
	'create_issue',
	'V1\Backoffice\IssueController@create_issue'
);
Route::get('create_issue/{id}/sub_activity', 'V1\Backoffice\IssueController@get_sub_activity');
Route::get('create_issue/{id}/work_activity', 'V1\Backoffice\IssueController@get_work_activity');
Route::get(
	'data_issue',
	'V1\Backoffice\IssueController@issue'
);

// Cetak isu report
Route::get('report_issue_teknologi/', 'V1\Backoffice\IssueController@cetak_laporan_isu_teknologi');
Route::get('report_issue_logistik', 'V1\Backoffice\IssueController@cetak_laporan_isu_logistik');
Route::get('report_issue_fabrikasi', 'V1\Backoffice\IssueController@cetak_laporan_isu_fabrikasi');
Route::get('report_issue_finishing', 'V1\Backoffice\IssueController@cetak_laporan_isu_finishing');
Route::get('report_issue_testing', 'V1\Backoffice\IssueController@cetak_laporan_isu_testing');

/* --------------------- End Issues --------------------- */

/* --------------------- Data Notification History --------------------- */
Route::resource('notifications', 'V1\Backoffice\NotificationController');
Route::get(
	'warning_notifications',
	'V1\Backoffice\NotificationController@showWarning'
);
/* --------------------- ENd Notification History --------------------- */


/* --------------------- Reports Data --------------------- */
Route::resource('reports', 'V1\Backoffice\ReportController');
/* --------------------- End Report Data --------------------- */


/* --------------------- Histories Data --------------------- */
Route::resource('histories', 'V1\Backoffice\HistoryController');
Route::get('report_histories_teknologi', 'V1\Backoffice\HistoryController@cetak_laporan_teknologi');
Route::get('report_histories_logistik', 'V1\Backoffice\HistoryController@cetak_laporan_logistik');
Route::get('report_histories_fabrikasi', 'V1\Backoffice\HistoryController@cetak_laporan_fabrikasi');
Route::get('report_histories_finishing', 'V1\Backoffice\HistoryController@cetak_laporan_finishing');
Route::get('report_histories_testing', 'V1\Backoffice\HistoryController@cetak_laporan_testing');
/* --------------------- End Report Data --------------------- *

Route::get('/home', 'HomeController@index')->name('home');

/* --------------------- Pie chart detail --------------------- */

Route::get('
	dashboard_divisions/{id}/{status_name}/{division_id}', 'V1\Backoffice\ProjectController@showDetailPieChartAdmin');

Route::get('
    dashboard_divisions/{id}/{status_name}', 'V1\Backoffice\ProjectController@showDetailPieChartDivision');

/* --------------------- End Pie chart detail --------------------- */

/* --------------------- Count At Sidebar --------------------- */

Route::get(
	'count_finish',
	'V1\Backoffice\NotificationController@countFinish'
);

Route::get(
	'count_warning',
	'V1\Backoffice\NotificationController@countWarning'
);

Route::get(
	'count_late',
	'V1\Backoffice\NotificationController@countLate'
);

Route::get(
	'count_issue',
	'V1\Backoffice\NotificationController@countIssue'
);
/* --------------------- End Count At Sidebar --------------------- */

/* --------------------- Count At Navbar --------------------- */
Route::get(
	'notif',
	'V1\Backoffice\NotificationController@show'
);
/* --------------------- End Count At Navbar --------------------- */


/* ---------------------  Division Additional --------------------- */

app/Http/Controllers/V1/Backoffice/AuthController.php
<?php

namespace App\Http\Controllers\V1\Backoffice;

use App\Entities\Division;
use App\Entities\Role;
use App\Entities\Project;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;

class AuthController extends Controller
{
    /**
     * Show the page registration.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $user = User::with(['get_role'])->orderBy('users.id','DESC')->get();
        return view('backoffice.users.data_users', compact('user'));
    }

    /**
     * Show the form registration.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function showFormRegister()
    {
        $project    = Project::all();
        $role       = Role::all();
        $division   = Division::all();
        return view('backoffice.users.register', compact('role','division','project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'          => 'required', 'string', 'max:255',
            'username'      => 'required', 'string', 'max:255',
            'nip'           => 'required', 'max:255', 'unique:users',
            'phone'         => 'required', 'max:15',
            'email'         => 'required', 'string', 'email', 'max:255', 'unique:users',
            'password'      => 'required', 'string', 'min:3',
            'division_name' => 'required',
            'role_id'       => 'required',
        ]);

        $user = new User([
            'name'          => $request->get('name'),
            'username'      => $request->get('username'),
            'nip'           => $request->get('nip'),
            'email'         => $request->get('email'),
            'phone'         => $request->get('phone'),
            'division_name' => $request->get('division_name'),
            'password'      => Hash::make($request->get('password')),
            'role_id'       => $request->get('role_id'),
            'project_to_pm' => $request->get('project_to_pm'),
        ]);
        $user->save();
        alert()->success('Successfully Add Data.', 'Success!');
        return redirect('/auths');
    }

    /**
     * Show the form for editing user.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user       = User::find($id);
        $role       = Role::all();
        $project    = Project::all();
        $division   = Division::all();
        return view('backoffice.users.edit', compact('user','role','division','project'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        if(empty($request->password)){
            $user->name         = $request->get('name');
            $user->username     = $request->get('username');
            $user->nip           = $request->get('nip');
            $user->email         = $request->get('email');
            $user->phone         = $request->get('phone');
            $user->division_name = $request->get('division_name');
            $user->role_id       = $request->get('role_id');
            $user->project_to_pm = $request->get('project_to_pm');
            $user->save();
        } else {
            $user->name         = $request->get('name');
            $user->username     = $request->get('username');
            $user->nip           = $request->get('nip');
            $user->email         = $request->get('email');
            $user->phone         = $request->get('phone');
            $user->division_name = $request->get('division_name');
            $user->password      = Hash::make($request->get('password'));
            $user->role_id       = $request->get('role_id');
            $user->project_to_pm = $request->get('project_to_pm');
            $user->save();
        }
        alert()->success('Successfully Update Data.', 'Success!');
        return redirect('/auths');
    }


    /** 
     * Remove the specified resou   rce from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        alert()->success('Successfully Remove Data.', 'Success!');
        return redirect('/auths');
    }


}

app/Http/Controllers/V1/Backoffice/MasterDataController.php
<?php

namespace App\Http\Controllers\V1\Backoffice;

use App\Http\Controllers\Controller;
use App\Entities\Activity;
use App\Entities\WorkActivity;
use App\Entities\SubActivity;
use Illuminate\Http\Request;
use PDF;
use DB;

class MasterDataController extends Controller
{
    /**
     * master activity page all
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $activities = Activity::with('get_division')->get();
        return view('backoffice.masters.master_activity', compact('activities'));
    }

    /**
     * master sub activity page all
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function showSubActivity(Request $request)
    {
        $sub_activities = SubActivity::with('get_activity')->get();
        return view('backoffice.masters.master_sub_activity', compact('sub_activities'));
    }


    /**
     * master sub activity page all
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function showWorkActivity(Request $request)
    {
        $work_activities = WorkActivity::with('get_sub_activity')->get();
        return view('backoffice.masters.master_work_activity', compact('work_activities'));
    }

    public function cetak_laporan_activity()
    {
        $activities = Activity::with('get_division')->get();
        ini_set('memory_limit', '8192M');
        $pdf = PDF::loadview('backoffice.masters.report_master_activity', ['activities'=>$activities]);
        set_time_limit(600);
        return $pdf->download('report-master-activity.pdf');

    }

    public function cetak_laporan_sub_activity()
    {
        $sub_activities = SubActivity::with('get_activity')->get();
        ini_set('memory_limit', '8192M');
        $pdf = PDF::loadview('backoffice.masters.report_master_sub_activity', ['sub_activities'=>$sub_activities]);
        set_time_limit(600);
        return $pdf->download('report-master-sub-activity.pdf');

    }

    public function cetak_laporan_work_activity()
    {
        $work_activities = WorkActivity::with('get_sub_activity')->get();
        ini_set('memory_limit', '8192M');
        $pdf = PDF::loadview('backoffice.masters.report_master_work_activity', ['work_activities'=>$work_activities]);
        set_time_limit(600);
        return $pdf->download('report-master-work-activity.pdf');

    }
}

resources/views/backoffice/activities/activity.blade.php
@extends('layouts.backend.masterPage')
@section('content')
<div class="section-header">
    <h1 class="titleC">{{$division->name}}</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active">
            <ol style="background:#38ada9" class="breadcrumb text-white-all">
                <li class="breadcrumb-item"><a href="/backoffice"><i class="fas fa-tachometer-alt"></i> Home</a></li>
                <li class="breadcrumb-item"><a href="/dashboard_divisions/{{$division->get_project->id}}"> Dashboard Division</a></li>
            </ol>
        </div><br>
    </div>

</div>
<div class="card top">
    <div class="card-body">
        <div class="col-lg-12">
            @foreach($project as $index => $row)
            <h6 class="titleC text-center"> {{$row->project_name}}</h6>
            @endforeach

            <div style="margin-right:3%" class="section-header-breadcrumb">
                <div class="bottom">
                   <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                     + Add Activity
                    </button>
                </div>
            </div>

                            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" data-backdrop="false" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Activity</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>

                    <form class="form-class" id="modal-login-part" method="post" action="{{ route('activities.store') }}">

                      <div class="modal-body">

                            @csrf
                            
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" class="form-control" required="true" name="name">
                                </div>
                                <div class="form-group">
                                    <input type="hidden" value="{{$division_id}}" class="form-control"   name="division_id">
                                </div>       
            
                    
                         </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" id="save" disabled="true" class="btn btn-primary">Save changes</button>
                      </div>
                  </form>
                </div>
              </div>
            </div>

            <!-- Form Modal Activity -->
           <!-- <form class="modal-part" id="modal-login-part" method="post" action="{{ route('activities.store') }}">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" required="true" name="name">
                    </div>
                    <div class="form-group">
                        <input type="hidden" value="{{$division_id}}" class="form-control" name="division_id">
                    </div>
                </div>        
            
            </form>
            -->

            <!-- End Form Modal Activity -->

            <div class="table-responsive">
                <table class="table col-lg-12 zero-configuration" id="table1">
                @include('sweet::alert')

                    <thead>
                        <tr>
                            <th width="10%">No.</th>
                            <th width="50%">Name</th>
                            <th width="40%">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach($progress as $index => $row)
                        <tr>
                            <td>{{$index+1}}</td>
                            <td>
                                @if ($row->jumlah != null || $row->total != 0)
                                    <?php
                                        $jumlah = $row->jumlah;
                                        $total = $row->total;
                                        $hasil = $jumlah / $total * 100;
                                        ?>
                                    <h6 class="title"> {{$row->name}} <span class="pull-right"><?php echo number_format((float) $hasil, 2, '.', ''); ?> %</span></h6>
                                    <div class="progress mb-3" style="height: 7px">
                                        <div class="progress-bar bg-primary" style="width: <?php echo number_format((float) $hasil, 2, '.', ''); ?>%;" role="progressbar">
                                        </div>
                                    </div>

                                @else
                                    <h6 class="title"> {{$row->name}} <span class="pull-right">0%</span></h6>
                                    <div class="progress mb-3" style="height: 7px">
                                        <div class="progress-bar bg-primary" style="width: 0%;" role="progressbar">
                                        </div>
                                    </div>
                                @endif
                            </td>
                            <td>
                                @if(!empty($row->id))
                                    <form id="delete{{$index}}" action="{{ route('activities.destroy', $row->id)}}" method="post">
                                        @csrf
                                        @method('DELETE')

                                        @if (Auth::user()->role_id != 1)
                                        @else
                                            <a>
                                                <button name="button" class="btn btn-icon btn-danger" type="button">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </a>

                                            <a href="{{ route('activities.edit', $row->id)}}">
                                                <button class="btn btn-icon btn-info" type="button">
                                                    <i class="fas fa-edit"></i>
                                                </button>
                                            </a>
                                             
                                        @endif
                                            </div>
     
                                            <a href="{{ route('activities.show',$row->id)}}">
                                                <button class="btn btn-icon btn-info" type="button">
                                                    <i class="fa fa-arrow-right"></i> Show Sub Activity
                                                </button>
                                            </a>
                                    </form>
                                @else
                                    <form>
                                        @if (Auth::user()->role_id != 1)
                                            <div style="display:none">
                                        @else
                                                <a href="#">
                                                    <button class="btn btn-icon btn-danger" type="submit">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </a>

                                                <a href="#">
                                                    <button class="btn btn-icon btn-info" type="button">
                                                        <i class="fas fa-edit"></i>
                                                    </button>
                                                </a>
                                        @endif
                                            </div>

                                            <a href="#">
                                                <button class=" btn btn-icon btn-info" type="button">
                                                    <i class="fa fa-arrow-right"></i> Show Sub Activity
                                                </button>
                                            </a>
                                    </form>
                                @endif

                            </td>
                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    
    var btn = document.getElementsByName('button');
   

    for (let i=0; i<btn.length; i++){
        

        document.getElementsByName('button')[i].addEventListener('click', function(){
            var id = i;
            
            swal({
                title: "are you sure for deleting this data ?",
                icon: "warning",
                buttons: true,
                dangerMode: true 
            })
            .then((willDelete)=>{
                if(willDelete){
                    document.getElementById('delete' + id).submit();  
                }
            });
        });
    }    


// for check value add of activity
document.getElementsByName('name')[0].addEventListener("keyup", event=> {

    
    if(event.target.value == "" ){
        document.getElementById('save').disabled = true;
    }
    else{
        document.getElementById('save').disabled = false;
    }

});

</script>
@endsection

resources/views/backoffice/activities/edit.blade.php
@extends('layouts.backend.masterPage')
@section('content')
<div class="section-header">
    <h1 class="titleC">{{$activity->name}}</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active">
            <a href="{{ URL::previous() }}" class="btn btn-info btn-sm"><i class="fa fa-arrow-left"></i> Back </a> </div> <br><br>
    </div>
</div>
<div class="card top">
    <div class="card-body">
        <h4 class="titleC text-center">Form Edit Category</h4><br>
        <div class="basic-form">
            <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{{ route('activities.update',$activity->id) }}">
                @method('PATCH')
                @csrf
                @if ($errors->any())
                <div class="col-md-10">
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                @endif
                <?php if(Auth::user()->role_id == 1) {?>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Name <span class="text-danger">*</span>
                    </label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" placeholder="Input category name" name="name" value="{{$activity->name}}">
                    </div><br>
                </div>
                <?php }?>


                <?php if(Auth::user()->role_id == 5) {?>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Picture <span class="text-danger">*</span>
                    </label>
                    <div class="col-sm-9">
                        <input type="file" class="form-control" name="picture">
                    </div><br>
                </div>
                <?php }?>

                <div class="form-group row">
                    <div class="col-sm-3">
                        <p></p>
                    </div>
                    <div class="col-sm-9">
                        <button type="submit" class="btn mb-1 btn-primary">Update</span>
                        </button>
                    </div>
                    <input type="hidden" value="{{ URL::previous() }}" name="url">
                </div>

            </form>
        </div>
    </div>
</div>
<!-- #/ container -->
@endsection